/**
 * This is a 128-bit Lehmer process, of which Park-Miller is a variant.
 */

import { Fraction } from "@gouvernathor/fraction.ts";
import AbstractRNG from "./abstract.js";
import hashString from "./hash-string.js";

export default class Lehmer128BigInt extends AbstractRNG {
    #state!: bigint;

    constructor(seed?: number|string) {
        super();
        this.seed = seed;
    }

    override set seed(seed: string | number | bigint | undefined) {
        if (seed === undefined) {
            seed = Math.floor(Math.random() * 0xffffffff);
        } else if (typeof seed === "string") {
            seed = hashString(seed);
        }
        if (typeof seed === "number") {
            // try to keep some of the complexity of decimal values
            const fract = Fraction.fromNumeric(seed);
            seed = fract.numerator ^ fract.denominator;
        }

        // the state must be seeded with an odd value
        this.#state = seed << 1n | 1n;
    }

    #next() {
        const mult = 0x12e15e35_b500f16e_2e714eb2_b37916a5n;
        // truncate to 128 bits to prevent memory leak
        this.#state = BigInt.asUintN(128, this.#state * mult);
        return this.#state >> 64n;
    }

    override random(resolution: bigint = this.resolution): Fraction {
        if (resolution <= 0n) {
            throw new Error("the resolution must be a strictly positive value");
        }

        // get the number of bits necessary to store `resolution` (log2())
        const nBits4 = resolution.toString(16).length * 4;
        // this rounds up to the higher 4-multiple, but we're rounding by 64 afterwards
        // (allegedly faster than .toString(2))

        // ceil the division by 64 (which is what is generated by #next)
        const numberOfNextCalls = Math.ceil(nBits4 / 64);

        // call #next that number of times
        const values = Array.from({ length: numberOfNextCalls }, this.#next.bind(this));

        // concatenate the bigints' bytes, becoming the numerator
        const numerator = values.reduce((prev, curr) => (prev << 64n) + curr);

        // the denominator is 2** (64 * the number of times #next was called)
        const denominator = 2n ** (64n * BigInt(numberOfNextCalls));

        return Fraction.fromPair(numerator, denominator);
    }
}
